package:
  name: libtiff
  version: 4.0.6

source:
  fn: tiff-4.0.6.tar.gz
  url: ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.6.tar.gz
  md5: d1d2e940dea0b5ad435f21f03d96dd72

build:
  number: 42

requirements:
  build:
    - zlib 1.2*
    - jpeg 8*
    - xz 5.2.*    # provides liblzma
  run:
    - zlib 1.2*
    - jpeg 8*
    - xz 5.2.*

about:
  home: http://www.libtiff.org/
  license: as-is (http://www.libtiff.org/misc.html)
